### ISSUE TITLE
add car sale advertisement image

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/carhouse-client#17]
I will get a selected file from form as MultipartFile object and then if this object is not empty I'l get bytes from it and set to car sale object to send to the server.
The form accepts .jpeg, .png and .webp formats, max size is 10MB
I need to add an image field to car sale object to send the image to the server
Server return image as a byte array and I'll convert it Base64 string format to display on the UI
If server don't return any image then I will set an image URL to default image from the internet

Estimation time: 4 hours

**Comment by maksimk99** [comment]
I need to resolve some issues according to the last pull request(how to notify a user about the error when he writes, update or delete a car sale advertisement comment)
To resolve it I'm going to create another RestTemplate object without any error handlers
and create an error response if the response status is not success on the UI
Is it ok? @aleksieiev

**Comment by aleksieiev** [comment]
Looks like issue about downloading image, but question is about some operations with comments.
Don't think it is connected. Am I wrong?

**Comment by maksimk99** [comment]
No, but as I understand it, I needed to add this to the next request.
Or it means I had to create the next pull request only for this issue?

**Comment by aleksieiev** [comment]
Different functionalities - different issues.
In general it had to be developed and implemented in scope of comment functionality development. If it was missed - ok, no problem, but currently it is independent part and can't be merged in scope of this task

**Comment by maksimk99** [comment]
ok
