### ISSUE TITLE
error response for operation with comments

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/carhouse-client#18]
I need to resolve some issues according to the last pull request(how to notify a user about the error when he writes, update or delete a car sale advertisement comment)
To resolve it I'm going to create another RestTemplate object without any error handlers
and create an error response if the response status is not success on the UI
Is it ok? @aleksieiev

**Comment by aleksieiev** [comment]
Not sure that it's possible to implement without error handlers.
Could you please share some details how it will be implemented in case of error on the server side?

**Comment by maksimk99** [comment]
```
function updateComment(commentId) {
        $.ajax({
            type: 'POST',
            url: "/carSale/comment/" + commentId,
            data: $('#updateForm').serialize(),
            success: function(data){
                $('#comment' + commentId).replaceWith(data);
                $('#updateDialog').modal('toggle');
            },
            error:function(){
                alert("error");
                $('#updateDialog').modal('toggle');
            }
        });
    }
```
Something like this, when response status is not OK error section will execute

**Comment by aleksieiev** [comment]
Who will generate incorrect HTTP status?
As far as I understand currently the next chain exists:
browser -> carhouse-app -> REST app

When request is on the carhouse app there won't be exception handlers, but it's required to handle 4** statuses from REST app. This part of code con't be able to do this.
So, what kind of improvement do you propose?

**Comment by maksimk99** [comment]
I'll add a condition in controller advice to return error fragment if exception comes from Comment controller otherwise error page
thanks to this I will be able to send an error response from comment controller to the browser

**Comment by aleksieiev** [comment]
Why do you prefer this solution instead of `RestTemplate` with `ResponseErrorHandler`?

**Comment by maksimk99** [comment]
Because I already have Controller Advice, and I need to change only a response entity name for comment controller without writing a new one

**Comment by aleksieiev** [comment]
Ok, sounds like a plan
