### ISSUE TITLE
Add one page with appropriate handled exception from REST service

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/carhouse-client#9]
As a user I want to see correct page with appropriate error message in case of third party service error. Currently the easiest way is to send `GET {service-url}/carSale/235243634` where `235243634` is `id` of any absent sale.
Use for this current build of `dev` branch with this [PR](https://github.com/java-fat-unicorn-team/CarSale/pull/33) code.

**Expected result**: valid HTML with error message from third-party service.

**Comment by maksimk99** [comment]
Resolved
